language: node_js

node_js:
  - '0.10'

before_install:
 - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
 - sudo apt-get update

install:
  - sudo apt-get install --force-yes libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2
  - npm install -g node-gyp
  - node-gyp install
  - npm install

script:
  - make
